### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by GARLICDOG** [Brawl345/Bunpro-Checker#2]
Hey,

I get a red tag on my extension icon in Chrome (updated to current version) saying "ERR".

Steps followed:
1. Add extension
2. Options --> add my API key (from the link in the page by going to BunPro)
3. Save
4. Right click on the extension --> check now

After the set intervals it also won't update.

Tried re-generating my API key in BunPro and re-adding it, didn't work.

Would also add this might not be an issue with the plugin. I have another 3rd party plugin using the BunPro API key and it seems to have stopped working as of last week.

**Comment by Brawl345** [comment]
The API for getting user reviews doesn't seem to work anymore. Not sure if this is an error on bunpro's side or if it's permanently gone. Nothing I can do, they don't seem to have any official API :/

**Comment by GARLICDOG** [comment]
Hey, seem to have been a temporary issue. Opened a thread in BunPro forums and after a few days it's working again.
